### ISSUE TITLE
Script is giving pyngrok.exception.PyngrokNgrokInstallError

### ISSUE THREAD

**Issue by 1trackprojects1** [JaniniRami07/FlaskLocator#1]
So I tried to manually download the file it was trying to request and it worked but however with the script it isn't working.

```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyngrok/installer.py", line 102, in install_ngrok
    download_path = _download_file(url, timeout)
  File "/usr/local/lib/python3.7/site-packages/pyngrok/installer.py", line 167, in _download_file
    raise e
  File "/usr/local/lib/python3.7/site-packages/pyngrok/installer.py", line 158, in _download_file
    shutil.copyfileobj(response, f)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FlaskLocator.py", line 18, in <module>
    ngrok_link = ngrok.connect(80, "http", region=region)
  File "/usr/local/lib/python3.7/site-packages/pyngrok/ngrok.py", line 183, in connect
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/usr/local/lib/python3.7/site-packages/pyngrok/ngrok.py", line 133, in get_ngrok_process
    ensure_ngrok_installed(ngrok_path)
  File "/usr/local/lib/python3.7/site-packages/pyngrok/ngrok.py", line 81, in ensure_ngrok_installed
    install_ngrok(ngrok_path)
  File "/usr/local/lib/python3.7/site-packages/pyngrok/installer.py", line 110, in install_ngrok
    raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))
pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip: The read operation timed out```

Ngrok is already installed though on the system.

**Comment by JaniniRami07** [comment]
I have just uploaded a fix for pyngrok errors that are showing for some Linux users, so make sure your on v.2.1 of FlaskLocator. 
If you still have the same problem this might help, https://github.com/dper/pumptweet/issues/39#issuecomment-576716321/

**Comment by 1trackprojects1** [comment]
Thank you for the reply. I am running mac and alright i will try once again and update you accordingly.

**Comment by 1trackprojects1** [comment]
Okay the update seems to fix my issue thank you. Please mark this as resolved :)
