### ISSUE TITLE
Flask Locator not working 

### ISSUE THREAD

**Issue by SamTheFinesser** [JaniniRami07/FlaskLocator#4]
Running on a windows laptop using all updated versions of requirements.txt
Using python 3.8.2 

Sending email to (my email)
Traceback (most recent call last):
  File "C:\Program Files\Python\FlaskLocator.py", line 243, in <module>
    sendMail(getJsonData.sender_mail, getJsonData.receiver_mail, getJsonData.password)
  File "C:\Program Files\Python\FlaskLocator.py", line 64, in sendMail
    with open(log_file, 'rb') as attachment:
FileNotFoundError: [Errno 2] No such file or directory: 'log.txt'

keep getting this error. also the links that are generated keep on showing 404 error code

**Comment by JaniniRami07** [comment]
Did anybody open the link?, I guess what is wrong is that your trying to send the log file  to your email but it doesn't exist, as the program only writes the log.txt file when it receives info from the phishing page and you didn't receive any to get saved in the log.txt file.

**Comment by SamTheFinesser** [comment]
Hi thanks for responding, I tested the link on my self and another friend, he clicked the link and it would say “404 error not found” is that normal? If it is right after I enter my email details it still shows that error above and I’ve done everything correct I swear.

**Comment by SamTheFinesser** [comment]
After they click the link am I supposed to wait for the program to initiate something on its own or do I simply just press CTRL + C and enter my email information?

**Comment by JaniniRami07** [comment]
Hey, does the program show something like this : [![Screenshot from Gyazo](https://gyazo.com/9ec47d69437a4afe4548d7021e62d4c1/raw)](https://gyazo.com/9ec47d69437a4afe4548d7021e62d4c1) when the victim you open the link?

**Comment by JaniniRami07** [comment]
And make sure your not using an add-blocker ass it blocks the IP requests and breaks the tool.

**Comment by SamTheFinesser** [comment]
No it doesn’t how do I get it to do that

**Comment by JaniniRami07** [comment]
This will be printed automatically when you open the link, your problem may be using an addblocker try to turn it off or running the program again, if it still not working set line 32,33 in FlaskLocator.py to Flase and run the program again and tell me what error it shows.

**Comment by SamTheFinesser** [comment]
![D78E84A9-1714-446A-8178-D2088907B7F2](https://user-images.githubusercontent.com/64462160/80480863-69308380-891f-11ea-9069-37dd5a62ed9d.png)

Alright I’ll try it but this is what keeps popping up when I click a link. I’m starting to think maybe I didn’t install something correctly. But I’ll try your method now

**Comment by SamTheFinesser** [comment]
I’m looking at lines 32 and 33 I see “log.disabled = true” and “app.logger.disabled = true” do you mean line 30?

**Comment by JaniniRami07** [comment]
No, line 32 and 33 set them to False like that:
log.disabled = False
app.logger.disabled = False

**Comment by SamTheFinesser** [comment]
Alright I did exactly that now this is the new error


* Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
[2020-04-28 07:35:43,265] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Python\FlaskLocator.py", line 160, in index
    return render_template('main.html', value = getRedirect.redirect)
  File "C:\Program Files\Python\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Program Files\Python\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Program Files\Python\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Program Files\Python\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Program Files\Python\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Program Files\Python\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Program Files\Python\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.html
127.0.0.1 - - [28/Apr/2020 07:35:43] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [28/Apr/2020 07:35:43] "GET /favicon.ico HTTP/1.1" 404 -
[2020-04-28 07:37:30,186] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Python\FlaskLocator.py", line 160, in index
    return render_template('main.html', value = getRedirect.redirect)
  File "C:\Program Files\Python\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Program Files\Python\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Program Files\Python\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Program Files\Python\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Program Files\Python\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Program Files\Python\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Program Files\Python\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.html
127.0.0.1 - - [28/Apr/2020 07:39:40] "GET / HTTP/1.1" 500 -

**Comment by JaniniRami07** [comment]
Did you install the program via git clone https://github.com/JaniniRami07/FlaskLocator, because it seems that you dont have the template folder that contain the main.html file.

**Comment by SamTheFinesser** [comment]
I did instal it from git bash. Look the problem I kept getting when trying to first install FlaskLocator was that whenever I entered the commands in CMD it would keep saying “no such file or directory” so I had to manually place the requirements.txt in the right directory. I’m guess if I do the same with the template folder I have, it should work I’ll give it a try

**Comment by JaniniRami07** [comment]
Try it and tell me if it is working for you so I can close the issue!

**Comment by SamTheFinesser** [comment]
It worked thank you so much!!!!!
