### ISSUE TITLE
Error - Server bind - OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by filebe777** [JaniniRami07/FlaskLocator#5]
You can you it consecutively. you have o restart linux machine to be able to use again. Secondly, you can not sent to multiple targets 

[+]Press CTRL + C to go back to home screen.
 * Serving Flask app "FlaskLocator" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "FlaskLocator.py", line 224, in <module>
    flask_server()
  File "FlaskLocator.py", line 205, in flask_server
    app.run(host = '0.0.0.0', port=port_)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by alexdlaird** [comment]
I'm the developer of `pyngrok`, and my guess here is the use of `sudo` to execute. In a previous version fo `pyngrok` this caused issues, as `ngrok` was looking for the config file in the home directory, but it didn't exist for `root`'s home.

This has been resolved in the latest version of `pyngrok`, so my suggestion would be for the owner of the repo to bump the dependency version to at least 3.1.1 (4.0.x would be better but may have more breaking changes).

**Comment by JaniniRami07** [comment]
Thank you for your response, ill take a look at it and update it as soon as possible!

**Comment by 00itsm00** [comment]
Off topic apologies, anyone can help me on below issue. 
https://github.com/sympy/sympy_gamma/issues/157

Not getting any help from respective community that's why posting here.

Please help me if anyone can. Thanks.
